### ISSUE TITLE
Tgt crashes on target

### ISSUE THREAD

**Issue by Stori-kun** [mousseng/xitools#8] opened 2023-05-22 08:22 UTC
I saw this was an issue that is titled as solved or something close to it is. Whenever I target anything, it leaves me a very long string of text and then closes the entire addon. 
![Report](https://github.com/mousseng/xitools/assets/81950108/6a928fc8-dd2d-4c70-9586-65aa011400cb)

**Comment by Stori-kun** [comment] 2023-05-22 08:32
NVM! I'm on Horizon and just realized I have to use the first releases. Sorry about that. Please close/delete ><

**Comment by Chibloom** [comment] 2023-05-22 08:37
...Not really sure what playing horizon has to do with this but the issue is still relevant, had it on a diff p server but could not figure the cause

**Comment by Stori-kun** [comment] 2023-05-22 10:36
Well the intitial releases target works on Horizon. The one before it was all bundled together in XITools.

**Comment by mousseng** [comment] 2023-05-22 19:17
thanks for the report - this should be fixed in `v0.18`.

**Closed by mousseng** 2023-05-22 19:17 UTC
